### ISSUE TITLE
[AutoQueueTech] Pile Sorter issues

### ISSUE THREAD

**Issue by HorstdasPferd** [Velociraptor115-DSPModding/DSPMods#26] opened 2024-02-14 16:21 UTC
**Mod**
AutoQueueTech v0.0.4

**Describe the bug**
After updating Pile Sorter Lvl 5 Upgrade the Pile Sorter fails to stack at all or corrupts the save game.

The next tech isnt visible / available unless you use AutoQueueTech -> It seems like a hidden copy or sth. from Pile Sorter (Stacking to 7, Level 4-Icon and ongoing)
The Lvl 6 Upgrade is Green Science. 

**To Reproduce**
1.: Unlock Pile Sorters
2. Place Pile Sorters
3. research Upgrade lvl 5, 
4. wait for auto queue next pile sorter upgrade
5. see Error

**Expected behavior**
The Pile Sorter should pile correctly but it is not stacking. 

**Screenshots**

**Environment (please complete the following information):**
 - Game version: V0.10.29.21942
 - List of other installed mods:
 - Galactic Scale 2.13.1 
 none of the others changed it for me, using solely GS and AutoQueueTech and corresponding dependencies)
 
**Additional context**
It seems like it can break a savegame and idk how many more upgrades there are. 

Edit: Screenshot: 
https://imgur.com/a/hRkLTz5

**Comment by Velociraptor115** [comment] 2024-02-21 04:15
I'm going to start looking into the issues with AutoQueueTech and the pile sorter tech
Did your issue occur with just AutoQueueTech or only when both AutoQueueTech and GalacticScale 2 were active?

**Comment by K-DaK** [comment] 2024-02-21 17:49
I'm on 0.10.28.21950 and I do not have Galactic Scale installed. I have also seen the same hidden upgrade getting researched.
I have Pile sorter researched to lvl 5 and the hidden stack upgrade to max maybe. Don't remember. But the Mk3 sorter can pull 8/stack at it tells me. I have all 4 types of sorters scattered around here and there.  But I have not experienced any errors, yet.

**Comment by TheL0ki** [comment] 2024-02-22 11:34
+1 on 0.10.29.21950 and without GC. Noticed the same beheaviour today. AutoQueueTech goes for this research even when Pile Sorter Upgrade lvl 6 is already researched

![image](https://github.com/Velociraptor115-DSPModding/DSPMods/assets/14993611/40396088-f48b-4135-8df2-92f1c2a4ec9a)

Maybe a quick fix would be to ignore this particular research item as it seems to be a placeholder or a relict of some sort

**Comment by Velociraptor115** [comment] 2024-02-23 00:08
I see
Thanks for all the reports folks
I will try my best to get this fixed by this weekend

**Comment by Velociraptor115** [comment] 2024-02-23 07:38
I think I figured out what the issue is
Should have checked the code changes for the pile sorter patch like I usually do for every game patch
They've added an "IsObsolete" field to the techs

The next version should fix the issue, but please report in this thread if the issue still persists

**Closed** 2024-02-23 07:42 UTC
